// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oquudykujvqbwekduwrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdXVkeWt1anZxYndla2R1d3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDgyNjQsImV4cCI6MjA2OTA4NDI2NH0.1ouIB78lSEn2uj_D76pLI-QRAzU1RdQl8VlWRg2Ezp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});